services:
  customer_registration_postgres:
    image: postgres
    container_name: customer_registration_postgres
    restart: always
    ports:
      - 3255:5432
    volumes:
      - customer_registration_postgres:/var/lib/postgresql/data
    env_file:
      - .env


  customer_registration_app:
    container_name: customer_registration_app
    build: .
    ports:
      - 80:5000
    depends_on:
      - customer_registration_postgres
    env_file:
      - .env


volumes:
  customer_registration_postgres: