services:
  customer_registration_postgres:
    image: postgres
    container_name: customer_registration_postgres
    restart: always
    ports:
      - 3255:5432
    env_file:
      - .env.test


  customer_registration_app:
    container_name: customer_registration_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - customer_registration_postgres
    env_file:
      - .env.test